import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import '../controllers/app_controller.dart';
import '../models/workflow_state.dart';
import '../theme/app_colors.dart';
import '../theme/app_typography.dart';
import '../widgets/proof_card_widget.dart';

class ProofCardScreen extends StatelessWidget {
  const ProofCardScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final controller = context.watch<AppController>();
    final incident = controller.currentIncident;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Diagnostic Proof Card'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => controller.navigateToStage(KlyroStage.verifying),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined),
            tooltip: 'Share Proof',
            onPressed: () {
              _copyProofMarkdown(context, controller);
            },
          ),
        ],
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                'REPORT STAGE',
                style: AppTypography.badge.copyWith(
                  color: AppColors.primary,
                  letterSpacing: 1.2,
                ),
              ),
              const SizedBox(height: 6),
              Text('VERIFIED PROOF', style: AppTypography.h2),
              const SizedBox(height: 16),

              // The Hero Card
              ProofCardWidget(
                incident: incident,
                onShare: () => _copyProofMarkdown(context, controller),
              ),

              const SizedBox(height: 24),

              // Export & Action Buttons
              ElevatedButton.icon(
                onPressed: () => _copyProofMarkdown(context, controller),
                icon: const Icon(Icons.copy_outlined, size: 18),
                label: const Text('COPY EVIDENCE REPORT (MARKDOWN)'),
              ),

              const SizedBox(height: 12),

              OutlinedButton.icon(
                onPressed: () {
                  controller.resetDemo();
                },
                icon: const Icon(Icons.restart_alt, size: 18),
                label: const Text('RESET DEMO FLOW'),
                style: OutlinedButton.styleFrom(
                  foregroundColor: AppColors.textSecondary,
                  side: const BorderSide(color: AppColors.borderLight),
                ),
              ),

              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }

  void _copyProofMarkdown(BuildContext context, AppController controller) {
    final incident = controller.currentIncident;
    final markdown = '''
# ⚡ KLYRO PROOF CARD — ${incident.id}
**Status:** VERIFIED ✅
**Project:** `${incident.project}`
**Failure:** ${incident.failureName}

### Root Cause
> ${incident.rootCauseTitle}
**Confidence:** ${incident.confidence}%

### Causal Path
${incident.failurePathNodes.join(' ➔ ')}

### Verified Evidence
${incident.evidenceSignals.map((s) => '- [x] ${s.title}: ${s.subtitle}').join('\n')}

### Repair & Verification
- Patch: `${incident.patch.filename}` (+${incident.patch.additions} / -${incident.patch.deletions})
- Result: **${incident.verification.passedTests}/${incident.verification.totalTests} tests passed** (100% regression free)

*Generated by KLYRO — Don't guess the bug. Prove the cause.*
''';

    Clipboard.setData(ClipboardData(text: markdown));
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        backgroundColor: AppColors.surfaceElevated,
        content: Row(
          children: [
            const Icon(Icons.check_circle, color: AppColors.primary, size: 18),
            const SizedBox(width: 8),
            Text('Report copied to clipboard!', style: AppTypography.body),
          ],
        ),
        duration: const Duration(seconds: 2),
      ),
    );
  }
}
